"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, Copy, Network } from "lucide-react";
import { usd } from "@/lib/format";

type Member={id:string;uid:string;name:string;level:number;businessAmount:number;status:string;joinedAt:string};
type Team={referralLink:string|null;stats:{directTeamCount:number;totalNetworkCount:number;activeUsersCount:number;teamVolume:number};members:Member[]};

export default function ReferralTeamPage(){
  const router=useRouter();
  const [team,setTeam]=useState<Team|null>(null),[message,setMessage]=useState(""),[error,setError]=useState("");
  useEffect(()=>{fetch("/api/team").then(async r=>{const d=await r.json().catch(()=>({}));if(r.status===401){router.replace(`/auth?mode=login&returnTo=${encodeURIComponent("/profile/referral-team")}`);return;}if(!r.ok)throw new Error(d.error||"Team request failed");setTeam(d.team);}).catch(e=>setError(e instanceof Error?e.message:"Team request failed"));},[router]);
  const copy=async()=>{if(!team?.referralLink)return;await navigator.clipboard?.writeText(team.referralLink);setMessage("Referral link copied");};
  return <main className="profile-page min-h-screen px-4 py-4 text-white sm:px-6"><div className="mx-auto max-w-2xl"><header className="profile-glass rounded-[22px] p-4"><div className="flex items-center justify-between"><Link href="/profile" className="grid h-10 w-10 place-items-center rounded-xl border border-white/[.08] bg-black/25 text-[#18ff8a]"><ArrowLeft size={18}/></Link><div className="grid h-10 w-10 place-items-center rounded-xl border border-[#18ff8a]/20 bg-[#18ff8a]/10 text-[#18ff8a]"><Network size={18}/></div></div><h1 className="mt-5 text-2xl font-black">Referral & Team</h1></header>{error&&<p className="profile-glass mt-4 rounded-[22px] p-4 text-sm text-[#ff4f6d]">{error}</p>}{team&&<><section className="profile-glass mt-4 rounded-[22px] p-4"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Referral link</p><div className="mt-2 flex gap-2"><p className="min-w-0 flex-1 truncate text-sm font-bold text-white">{team.referralLink||"Unavailable"}</p><button onClick={copy} className="grid h-9 w-9 place-items-center rounded-xl bg-[#18ff8a] text-[#050608]"><Copy size={15}/></button></div>{message&&<p className="mt-2 text-xs font-bold text-[#18ff8a]">{message}</p>}</section><section className="mt-4 grid grid-cols-2 gap-3"><Stat label="Direct team" value={String(team.stats.directTeamCount)}/><Stat label="Total network" value={String(team.stats.totalNetworkCount)}/><Stat label="Active team" value={String(team.stats.activeUsersCount)}/><Stat label="Team volume" value={usd(team.stats.teamVolume)}/></section><section className="profile-glass mt-4 rounded-[22px] p-4"><div className="flex items-center justify-between gap-3"><h2 className="text-lg font-black">Team members</h2><Link href="/team/top-up" className="rounded-xl bg-[#18ff8a] px-3 py-2 text-[10px] font-black text-[#050608]">Top-up Team</Link></div><div className="mt-3 space-y-2">{team.members.length?team.members.map(m=><div key={m.id} className="rounded-2xl border border-white/[.08] bg-black/25 p-3"><div className="flex justify-between gap-3"><p className="font-bold text-white">{m.name}</p><span className="text-xs text-[#18ff8a]">{m.status}</span></div><p className="mt-1 text-xs text-slate-500">UID {m.uid} - Level {m.level}</p><p className="mt-1 text-xs text-slate-400">Business {usd(m.businessAmount)}</p></div>):<p className="rounded-2xl border border-white/[.08] bg-black/25 p-6 text-center text-sm text-slate-500">No team members</p>}</div></section></>}</div></main>;
}
function Stat({label,value}:{label:string;value:string}){return <div className="profile-glass rounded-[22px] p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-1 text-xl font-black text-white">{value}</p></div>}
