module.exports = {
  apps: [
    {
      name: "voltix-web",
      script: "node_modules/next/dist/bin/next",
      args: "start",
      cwd: __dirname,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 5000,
      max_memory_restart: "1G",
      kill_timeout: 30000,
      env: {
        NODE_ENV: "production",
        TZ: "UTC",
        TRADE_SETTLEMENT_ENABLED: "false",
        DATABASE_CONNECTION_LIMIT: "10",
        DATABASE_POOL_TIMEOUT_SECONDS: "10",
        DATABASE_CONNECT_TIMEOUT_SECONDS: "5",
      },
    },
    {
      name: "voltix-ai-auto-trade-worker",
      script: "node_modules/tsx/dist/cli.cjs",
      args: "scripts/ai-auto-trade-worker.ts",
      cwd: __dirname,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 5000,
      max_memory_restart: "512M",
      kill_timeout: 120000,
      env: {
        NODE_ENV: "production",
        TZ: "UTC",
        TRADE_SETTLEMENT_ENABLED: "false",
        DATABASE_CONNECTION_LIMIT: "4",
        DATABASE_POOL_TIMEOUT_SECONDS: "10",
        DATABASE_CONNECT_TIMEOUT_SECONDS: "5",
        AI_AUTO_TRADE_INTERVAL_MS: "30000",
      },
    },
    {
      name: "voltix-settlement-worker",
      script: "node_modules/tsx/dist/cli.cjs",
      args: "scripts/settlement-worker.ts",
      cwd: __dirname,
      instances: 2,
      exec_mode: "fork",
      autorestart: true,
      max_restarts: 20,
      restart_delay: 5000,
      max_memory_restart: "768M",
      kill_timeout: 180000,
      env: {
        NODE_ENV: "production",
        TZ: "UTC",
        TRADE_SETTLEMENT_ENABLED: "true",
        DATABASE_CONNECTION_LIMIT: "4",
        DATABASE_POOL_TIMEOUT_SECONDS: "10",
        DATABASE_CONNECT_TIMEOUT_SECONDS: "5",
        TRADE_SETTLEMENT_INTERVAL_MS: "2000",
        TRADE_SETTLEMENT_BATCH_SIZE: "1000",
      },
    },
  ],
};
