ALTER TABLE "Withdrawal"
  ADD COLUMN "eligibilityStatus" TEXT,
  ADD COLUMN "capitalAmount" DECIMAL(36,18) NOT NULL DEFAULT 0,
  ADD COLUMN "earnedProfit" DECIMAL(36,18) NOT NULL DEFAULT 0,
  ADD COLUMN "requiredProfit" DECIMAL(36,18) NOT NULL DEFAULT 0,
  ADD COLUMN "completedPercentage" DECIMAL(8,4) NOT NULL DEFAULT 0,
  ADD COLUMN "earlyWithdrawal" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "earlyWithdrawalCharge" DECIMAL(36,18) NOT NULL DEFAULT 0,
  ADD COLUMN "percentageFee" DECIMAL(36,18) NOT NULL DEFAULT 0,
  ADD COLUMN "fixedFee" DECIMAL(36,18) NOT NULL DEFAULT 0,
  ADD COLUMN "totalCharges" DECIMAL(36,18) NOT NULL DEFAULT 0,
  ADD COLUMN "netWithdrawalAmount" DECIMAL(36,18) NOT NULL DEFAULT 0,
  ADD COLUMN "earlyWithdrawalConfirmedAt" TIMESTAMP(3);
