-- Compatibility no-op.
-- A fresh database is initialized by 20260621100000_init with the current
-- TradeCode/CopyTrade schema already applied. This historical migration
-- previously assumed an older CodeStatus enum existed.
