-- Compatibility no-op.
-- A fresh database is initialized by 20260621100000_init with the current
-- Withdrawal schema already applied. This historical migration previously
-- assumed an older baseline enum/table existed and failed on fresh databases.
