ALTER TYPE "DepositStatus" ADD VALUE IF NOT EXISTS 'COMPLETED';
ALTER TYPE "DepositStatus" ADD VALUE IF NOT EXISTS 'UNDERPAID';
ALTER TYPE "DepositStatus" ADD VALUE IF NOT EXISTS 'OVERPAID';
ALTER TYPE "DepositStatus" ADD VALUE IF NOT EXISTS 'REVIEW_REQUIRED';

ALTER TABLE "Deposit"
  ADD COLUMN "signatureVerified" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "failureReason" TEXT;
