ALTER TYPE "DepositStatus" ADD VALUE IF NOT EXISTS 'PENDING';
ALTER TYPE "DepositStatus" ADD VALUE IF NOT EXISTS 'APPROVED';
ALTER TYPE "DepositStatus" ADD VALUE IF NOT EXISTS 'REJECTED';

ALTER TABLE "Deposit" ALTER COLUMN "txHash" DROP NOT NULL;
ALTER TABLE "Deposit" ALTER COLUMN "blockNumber" DROP NOT NULL;
