"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, LockKeyhole, ShieldCheck } from "lucide-react";

type SessionInfo={id:string;createdAt:string;expiresAt:string};

export default function SecurityPage(){
  const router=useRouter();
  const [sessions,setSessions]=useState<SessionInfo[]>([]),[currentPassword,setCurrentPassword]=useState(""),[newPassword,setNewPassword]=useState(""),[confirmPassword,setConfirmPassword]=useState(""),[loading,setLoading]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
  useEffect(()=>{fetch("/api/profile/security").then(async r=>{const d=await r.json().catch(()=>({}));if(r.status===401){router.replace(`/auth?mode=login&returnTo=${encodeURIComponent("/profile/security")}`);return;}if(r.ok)setSessions(Array.isArray(d.sessions)?d.sessions:[]);});},[router]);
  const change=async(e:FormEvent)=>{e.preventDefault();setError("");setMessage("");setLoading(true);const r=await fetch("/api/profile/password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({currentPassword,newPassword,confirmPassword})});const d=await r.json().catch(()=>({}));setLoading(false);if(!r.ok){setError(d.error||"Password change failed");return;}setCurrentPassword("");setNewPassword("");setConfirmPassword("");setMessage("Password changed");};
  const logoutAll=async()=>{setError("");setLoading(true);const r=await fetch("/api/profile/security",{method:"DELETE"});setLoading(false);if(!r.ok){const d=await r.json().catch(()=>({}));setError(d.error||"Logout all failed");return;}window.location.replace("/auth?mode=login");};
  return <Frame title="Security" icon={LockKeyhole}><form onSubmit={change} className="profile-glass rounded-[22px] p-4"><h2 className="text-lg font-black">Change password</h2><div className="mt-4 space-y-3"><Password label="Current password" value={currentPassword} onChange={setCurrentPassword}/><Password label="New password" value={newPassword} onChange={setNewPassword}/><Password label="Confirm password" value={confirmPassword} onChange={setConfirmPassword}/></div>{(error||message)&&<p className={`mt-3 text-xs font-bold ${error?"text-[#ff4f6d]":"text-[#18ff8a]"}`}>{error||message}</p>}<button disabled={loading} className="mt-4 w-full rounded-2xl bg-[#18ff8a] py-3.5 text-sm font-black text-[#050608] disabled:opacity-60">{loading?"Working...":"Change Password"}</button></form><section className="profile-glass mt-4 rounded-[22px] p-4"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-[#18ff8a]/10 text-[#18ff8a]"><ShieldCheck size={18}/></span><div><h2 className="font-black">Active sessions</h2><p className="text-xs text-slate-500">{sessions.length} active session(s)</p></div></div><div className="mt-3 space-y-2">{sessions.map(s=><div key={s.id} className="rounded-2xl border border-white/[.08] bg-black/25 p-3 text-xs text-slate-400"><p className="font-bold text-white">Session {s.id.slice(-6)}</p><p>Created {new Date(s.createdAt).toLocaleString()}</p><p>Expires {new Date(s.expiresAt).toLocaleString()}</p></div>)}</div><button onClick={logoutAll} disabled={loading} className="mt-4 w-full rounded-2xl border border-[#ff4f6d]/30 bg-[#ff4f6d]/10 py-3.5 text-sm font-black text-[#ff8aa0] disabled:opacity-60">Logout from all devices</button></section></Frame>;
}

function Frame({title,icon:Icon,children}:{title:string;icon:typeof LockKeyhole;children:React.ReactNode}){return <main className="profile-page min-h-screen px-4 py-4 text-white sm:px-6"><div className="mx-auto max-w-2xl"><header className="profile-glass rounded-[22px] p-4"><div className="flex items-center justify-between"><Link href="/profile" className="grid h-10 w-10 place-items-center rounded-xl border border-white/[.08] bg-black/25 text-[#18ff8a]"><ArrowLeft size={18}/></Link><div className="grid h-10 w-10 place-items-center rounded-xl border border-[#18ff8a]/20 bg-[#18ff8a]/10 text-[#18ff8a]"><Icon size={18}/></div></div><h1 className="mt-5 text-2xl font-black">{title}</h1></header><div className="mt-4">{children}</div></div></main>}
function Password({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="block text-xs font-bold text-slate-400">{label}<input type="password" value={value} onChange={e=>onChange(e.target.value)} className="mt-2 w-full rounded-2xl border border-white/[.08] bg-black/25 px-4 py-3 text-sm font-bold text-white outline-none focus:border-[#18ff8a]/50"/></label>}
