ALTER TYPE "CodeStatus" ADD VALUE IF NOT EXISTS 'USED';

ALTER TABLE "TradeCode"
  ADD COLUMN IF NOT EXISTS "vipRank" TEXT NOT NULL DEFAULT 'NONE',
  ADD COLUMN IF NOT EXISTS "tradeWindowMinutes" INTEGER NOT NULL DEFAULT 10;
